AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  petrol-price-api

  Sample SAM Template for petrol-price-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 600
    MemorySize: 128

Resources:
  UpdatePricesDatabase:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/update/
      Handler: fuelpriceservice
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        BookingEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /update
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          local: false
          update_sites: true
          api_key: ""
      Policies:
        - DynamoDBCrudPolicy:
            TableName: current_fuel_prices

  ReturnPricesDatabase:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/fetch/
      Handler: fuelpriceservice
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        PricesEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /prices
            Method: GET
          Parameters:
            Lati: Sting
        SitesEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sites
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabsW/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          local: false
          api_key: ""
      Policies:
        - DynamoDBCrudPolicy:
            TableName: current_fuel_prices

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FuelPriceAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{proxy+}/"

  UpdatePricesFunction:
    Description: "Fuel Prices Update Lambda Function ARN"
    Value: !GetAtt UpdatePricesDatabase.Arn
  UpdatePricesIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UpdatePricesDatabaseRole.Arn

  ReturnPricesFunction:
    Description: "Fuel Prices Update Lambda Function ARN"
    Value: !GetAtt ReturnPricesDatabase.Arn
  ReturnPricesIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ReturnPricesDatabaseRole.Arn
